baseURL = 'https://loganmcdonald.dev/'
languageCode = 'en-us'
title = 'Logan McDonald'
theme = 'custom'

[params]
  description = "Developer and writer sharing thoughts on engineering leadership, public service, and emerging technology."
  author = "Logan McDonald"
  images = ["images/social-preview.svg"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "writing"
    url = "/writing/"
    weight = 2
