baseURL = 'https://loganmcdonald.dev/'
languageCode = 'en-us'
title = 'Logan McDonald'
theme = 'custom'

[params]
  description = "Personal website and blog"
  author = "Logan McDonald"
  tagline = "Engineering leader and civil servant building and operating software for the people."
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "writing"
    url = "/writing/"
    weight = 2
